FROM fedora:latest

WORKDIR /app

RUN dnf update -y && \
    dnf install -y bash python3 python3-pip python3-devel gcc sqlite && \
    dnf clean all

RUN pip3 install Django==4.2.7

EXPOSE 8000

CMD ["python3", "manage.py", "runserver". "0.0.0.0:8000"]